import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";

interface HomeProps {
  day:
    | "Sunday"
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday";
  hours: number;
  minutes: number;
  imageUrl: string;
}

export default function Home({ day, hours, minutes, imageUrl }: HomeProps) {
  return (
    <>
      <Head>
        <title>Hosting a NextJs app on AWS App Runner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Today is {day}</p>
        <p>
          It&apos;s {hours}:
          {minutes.toLocaleString("en-US", {
            minimumIntegerDigits: 2,
          })}
        </p>
        <Image src={imageUrl} alt="a random image" width={500} height={500} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  const today = new Date();
  const day = days[today.getDay()];
  const hours = today.getHours();
  const minutes = today.getMinutes();

  console.log({ url: process.env.RANDOM_IMAGE_API_URL });
  const response = await fetch(process.env.RANDOM_IMAGE_API_URL!);
  const { url } = response;

  return { props: { day, hours, minutes, imageUrl: url } };
}
